/* tslint:disable */
import {DataContext} from '@/context';
import {Example} from '@/lib/types';
import { getYoutubeThumbnailUrl } from '@/lib/youtube';
import {useContext} from 'react';

export default function ExampleGallery({ title = 'Examples', selectedExample, onSelectExample }: { title?: string; selectedExample: Example | null; onSelectExample: (example: Example) => void; }) {
  const {examples} = useContext(DataContext);
  return (<div className="example-gallery"><h2 className="gallery-title">{title}</h2><div className="gallery-grid">{examples.map((example) => (<div key={example.title} className={`gallery-item ${selectedExample?.title === example.title ? 'selected' : ''}`} onClick={() => onSelectExample(example)}><div className="thumbnail-container"><img src={getYoutubeThumbnailUrl(example.url)} alt={example.title} className="thumbnail" /></div><div className="gallery-item-title">{example.title}</div></div>))}</div><style>{`.example-gallery{width:100%}.gallery-title{color:var(--color-text-primary);font-family:var(--font-secondary);font-size:1.2rem;font-weight:700;margin-bottom:var(--space-md);text-align:center}.gallery-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:var(--space-md)}.gallery-item{cursor:pointer;border:var(--border-width-sm) solid transparent;border-radius:var(--border-radius-md);display:flex;flex-direction:column;overflow:hidden;transition:background-color .2s,border-color .2s}.gallery-item:hover{background-color:var(--color-surface-1-active)}.gallery-item.selected{border-color:var(--color-accent);box-shadow:none}.gallery-item-title{align-items:center;background-color:var(--color-surface-1);color:var(--color-text-primary);display:flex;flex-grow:1;font-size:.9rem;font-weight:500;justify-content:center;padding:var(--space-sm);text-align:center;transition:background-color .2s}.gallery-item:hover .gallery-item-title{background-color:transparent}.thumbnail-container{position:relative;padding-top:56.25%;background-color:var(--color-surface-4);border-top-left-radius:var(--border-radius-md);border-top-right-radius:var(--border-radius-md);overflow:hidden}.thumbnail{position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover}`}</style></div>);
}